# Generated by Django 4.2.7 on 2024-01-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_user',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('CRM_admin', 'CRM_admin')], default=('user', 'user'), max_length=15),
        ),
    ]
