# Generated by Django 4.2.7 on 2024-01-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_user_status_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id']},
        ),
    ]
