version: '3.1'

services:

  db:
    env_file:
      - password.env
    image: postgres:14.10
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /opt/homebrew/var/postgresql@14
    ports:
      - '54321:5432'
#    volumes:
#      - /opt/homebrew/var/postgresql@14:/var/lib/postgresql/data